-- Migration: Insert recipes data
-- Purpose: Insert 30 hiver recipes and 30 printemps recipes from recipes.md
-- Risk: Low - data insertion only

-- Helper function to escape single quotes in SQL strings
-- Note: PostgreSQL uses single quotes, so we need to escape them by doubling them

-- Insert Hiver recipes (1-10)
INSERT INTO public.recipes (title, category, total_time, portions, benefits, ingredients, preparation, period) VALUES
('Ragoût de dinde, potimarron et riz complet', 'Soutien digestif', '30 min', '3 portions', 'Doux pour l''estomac, riche en fibres et en vitamines A et K.', '250 g de dinde, 150 g de potimarron cuit, 100 g de riz complet bien cuit, 1 c. à café d''huile de colza (oméga-3), 1 pincée de romarin séché', '1. Cuire la dinde **à cœur** dans de l''eau bouillante. 2. Cuire à la vapeur ou à l''eau les légumes jusqu''à ce qu''ils soient tendres. 3. Écraser grossièrement le tout ou couper en petits morceaux. 4. Ajouter l''huile et les graines une fois le tout refroidi.', 'hiver'),
('Hachis de bœuf, carottes, patate douce & thym', 'Soutien digestif, peau & poils', '20 min', '3 portions', 'Bon pour l''énergie et la peau (vitamines B, bêta-carotène), soutien digestif.', '250 g de bœuf maigre haché –120 g de patate douce –80 g de carottes –1 c. à café d''huile de lin –1 pincée de thym séché –', '1. Faire cuire la viande jusqu''à cuisson complète à cœur à la vapeur ou dans de l''eau bouillante. 2. .Cuire les légumes à la vapeur. 3. Mélanger et parsemer de thym, puis ajouter l''huile après refroidissement.', 'hiver'),
('Poulet, panais, épinards & levure de bière', 'Peau & poils', '40 min', '3 portions', 'Bon pour le poil et les griffes, riche en fer et vitamines du groupe B.', '250 g de blanc de poulet – 100 g de panais – 50 g d''épinards – 1 c. à café d''huile de saumon – 1 c. à café de levure de bière', '1. Cuire le poulet **à cœur** dans l''eau bouillante. 2. Cuire le panais à la vapeur, ajouter les épinards en fin de cuisson (1 à 2 minutes). 3.Mélanger le tout, puis ajouter la levure et l''huile.', 'hiver'),
('Agneau, topinambour, pomme & romarin', 'Anti-constipation', '25 min', '3 portions', 'Bon pour le microbiote, goût très apprécié.', '250 g d''agneau maigre (collier ou épaule) – 100 g de topinambour –80 g de pomme (sans pépin, pelée) – 1 c. à café d''huile de chanvre – 1 pincée de romarin séché', '1. Cuire l''agneau **à cœur**, coupé en petits morceaux (vapeur ou eau bouillante) 2. Cuire les légumes et la pomme à la vapeur. 3. Ajouter les herbes et l''huile une fois refroidi.', 'hiver'),
('Colin, riz complet, brocoli & ortie séchée', 'Articulaire, chien senior', '35 min', '3 portions', 'Soutien articulaire, bon pour les chiens seniors ou stérilisés.', '250 g de colin (ou cabillaud) – 100 g de riz complet bien cuit – 80 g de brocoli – 1 c. à café d''huile de sardine – 1 pincée d''ortie séchée (bio)', '1. Cuire le poisson à la vapeur ou pochage, jusqu''à ce qu''il s''émiette facilement. 2. Cuire le riz et les brocolis à l''eau. 3. Mélanger le tout, parsemer d''ortie et verser l''huile.', 'hiver'),
('Velouté réconfortant au panais, cabillaud et persil', 'Digestion et anti-diarrhée', '30 min', '3 portions', 'digestion douce et effet anti-diarrhéique', '250 g de filet de cabillaud (cuit à cœur à la vapeur) - 150 g de panais (cuit à l''eau ou vapeur)- 100 g de carottes (vapeur) - 1 c. à café d''huile de lin - 1 c. à soupe de persil frais ciselé (ajouté après cuisson)', '1. Cuire le cabillaud à la **vapeur douce**, jusqu''à ce qu''il s''émiette facilement. 2. Cuire le panais et les carottes à la **vapeur ou à l''eau bouillante** jusqu''à ce qu''ils soient bien tendres. 3. Mixer ou écraser grossièrement le tout. 4. Ajouter le persil ciselé et l''huile une fois tiédi.', 'hiver'),
('Bowl énergisant au hareng, épinards et patate douce', 'Energie, articulations', '20 min', '3 portions', 'boost d''énergie + soutien articulaire.', '250 g de hareng cuit à cœur (sans arêtes, nature) - 150 g de patate douce - 100 g d''épinards frais - 1 c. à café d''huile de saumon - 1 pincée de gingembre frais râpé (facultatif)', '1. Cuire le hareng à la **vapeur ou à l''eau bouillante**, jusqu''à cuisson complète. 2. Cuire la patate douce à la **vapeur**. 3. Blanchir les épinards 1 min à l''eau chaude. 4.Mélanger, ajouter l''huile et le gingembre une fois refroidi.', 'hiver'),
('Purée douceur à la dinde, céleri-rave et courge butternut', 'Digestion, Ballonnements', '25 min', '3 portions', 'Doux pour l''estomac, soulage les ballonnements.', '250 g de blanc de dinde - 100 g de courge butternut - 100 g de céleri-rave - 1 c. à café d''huile de coco - 1 c. à café de graines de fenouil moulues', '1. Cuire la dinde à cœur à **l''eau bouillante**. 2. Cuire courge et céleri-rave à la **vapeur douce**. 3. Écraser en purée ou mixer. 4. Ajouter l''huile et le fenouil après refroidissement.', 'hiver'),
('Wok d''hiver au bœuf, choux de Bruxelles et navet', 'Peau & poils', '35 min', '3 portions', 'soutien peau & poil, anti-carences hivernales.', '250 g de bœuf maigre haché - 100 g de choux de Bruxelles - 100 g de navets - 1 c. à café d''huile de cameline - 1 pincée de curcuma (facultatif)', '1. Cuire le bœuf à cœur à la **vapeur** ou à **l''eau**, en petits morceaux. 2. Cuire les légumes à la **vapeur douce**. 3. Mélanger, puis ajouter huile et curcuma une fois tiédi.', 'hiver'),
('Repas vitalité aux œufs, topinambour et brocoli', 'Immunitaire, microbiote intestinal', '40 min', '3 portions', 'Riche en fer', '2 œufs bio durs par portion (6 œufs au total) - 100 g de topinambour - 100 g de brocoli - 1 c. à café d''huile de colza - 1 pincée de levure de bière', '1. Cuire les œufs à **l''eau bouillante 10 minutes**, les écaler. 2. Cuire topinambour et brocoli à la **vapeur**, bien tendres. 3. Écraser ou hacher les œufs, mélanger avec les légumes. 4. Ajouter huile et levure après refroidissement.', 'hiver');

-- Insert Hiver recipes (11-20)
INSERT INTO public.recipes (title, category, total_time, portions, benefits, ingredients, preparation, period) VALUES
('Soupe de poulet, carotte et riz', 'Confort digestif', '30 min', '3 portions', 'très digeste, idéal après un épisode de diarrhée.', '250 g de blanc de poulet - 100 g de carottes - 100 g de riz blanc - 1 c. à café d''huile de lin - 1 pincée de fenouil moulu', '1. Cuire le poulet à cœur à l''eau bouillante. 2. Cuire les carottes à la vapeur ou à l''eau. 3. Faire cuire le riz longuement jusqu''à ce qu''il soit bien tendre. 4. Mélanger tiède, ajouter l''huile et le fenouil juste avant de servir.', 'hiver'),
('Colin, courge musquée et flocons d''avoine', 'Confort digestif', '25 min', '3 portions', 'doux pour l''estomac et riche en fibres solubles.', '250 g de filet de colin - 150 g de courge musquée - 80 g de flocons d''avoine - 1 c. à café d''huile de colza - 1 pincée de coriandre moulue', '1. Cuire le poisson à la vapeur jusqu''à ce qu''il s''émiette facilement. 2. Cuire la courge à la vapeur. 3. Faire cuire les flocons à l''eau. 4. Mélanger, ajouter l''huile et la coriandre une fois tiède.', 'hiver'),
('Topinambour, agneau et brocoli', 'Microbiote et transit', '25 min', '3 portions', 'riche en inuline, bon pour les bonnes bactéries intestinales.', '250 g d''agneau- 100 g de topinambour - 100 g de brocoli - 1 c. à café d''huile de chanvre - 1 pincée de levure de bière', '1. Cuire l''agneau à cœur à la vapeur. 2. Cuire les légumes à la vapeur douce. 3. Écraser ou couper finement. 4. Ajouter huile et levure après refroidissement.', 'hiver'),
('Dinde, betterave et quinoa', 'Microbiote et transit', '35 min', '3 portions', 'facilite le transit, riche en fibres douces.', '1. 250 g de filet de dinde 2. 100 g de betterave cuite 3. 100 g de quinoa 4. 1 c. à café d''huile de sardine 5. 1 pincée de graines de chia (facultatif)', '1. Cuire la dinde à cœur dans l''eau. 2. Cuire le quinoa très soigneusement, bien rincé. 3. Écraser la betterave. 4. Mélanger, puis ajouter huile et chia à froid.', 'hiver'),
('Maquereau, panais et épinards', 'Peau, pelage & mue', '25 min', '3 portions', 'stimule la repousse du poil, bon pour les chiens à la peau sèche.', '250 g de maquereau - 120 g de panais - 80 g d''épinards - 1 c. à café d''huile de cameline - 1 pincée de thym', '1. Cuire le poisson à la vapeur, sans arêtes. 2. Cuire le panais à la vapeur. 3. Blanchir les épinards rapidement à l''eau bouillante. 4. Mélanger tiède, ajouter huile et thym.', 'hiver'),
('Sardines, céleri-rave et patate douce', 'Peau, pelage & mue', '20 min', '3 portions', 'bon pour les peaux sèches et la mue saisonnière.', '250 g de sardines (vapeur, sans arêtes) - 100 g de patate douce (vapeur) - 100 g de céleri-rave (vapeur) - 1 c. à café d''huile de lin - 1 c. à café de spiruline (facultatif)', '1. Cuire les sardines à la vapeur, sans arêtes. 2. Cuire les légumes à la vapeur douce. 3. Écraser, ajouter huile et spiruline une fois refroidi.', 'hiver'),
('Bœuf, carotte, navet & ortie', 'Immunité et énergie', '25 min', '3 portions', 'tonifiant naturel, reminéralisant.', '250 g de bœuf maigre haché - 100 g de carottes - 100 g de navets - 1 c. à café d''huile d''olive - 1 pincée d''ortie séchée', '1. Cuire le bœuf à cœur à la vapeur. 2. Cuire les légumes à la vapeur douce. 3. Mélanger, puis ajouter l''ortie et l''huile une fois tiédi.', 'hiver'),
('Œufs durs, courge, fenouil & curcuma', 'Immunité et énergie', '25 min', '3 portions', 'riche en antioxydants, booste les défenses naturelles.', '6 œufs bio - 100 g de courge butternut - 100 g de fenouil - 1 c. à café d''huile de colza - 1 pincée de curcuma', '1. Cuire les œufs 10 min à l''eau bouillante. 2. Cuire les légumes à la vapeur. 3. Écaler les œufs, les hacher. 4. Mélanger avec les légumes, ajouter huile et curcuma à froid.', 'hiver'),
('Veau, brocoli et flocons d''avoine', 'Articulations, seniors', '20 min', '3 portions', 'articulations et anti-inflammatoire naturel.', '250 g de veau - 100 g de brocoli - 80 g de flocons d''avoine - 1 c. à café d''huile de sardine - 1 pincée de gingembre', '1. Cuire le veau à cœur à la vapeur. 2. Cuire le brocoli à la vapeur douce. 3. Cuire les flocons à l''eau. 4. Mélanger, puis ajouter huile et gingembre.', 'hiver'),
('Tajine doux d''agneau, topinambour et navet', 'Articulations, seniors', '20 min', '3 portions', 'anti-ballonnements, riche en fibres prébiotiques.', '250 g d''agneau - 100 g de topinambour - 100 g de navet - 1 c. à café d''huile de coco - 1 pincée de cannelle', '1. Cuire l''agneau à cœur à la vapeur. 2. Cuire les légumes à la vapeur. 3. Écraser légèrement, ajouter huile et cannelle après refroidissement.', 'hiver');

-- Insert Hiver recipes (21-30)
INSERT INTO public.recipes (title, category, total_time, portions, benefits, ingredients, preparation, period) VALUES
('Dinde, courge musquée & fenouil', 'Énergie', '25 min', '3 portions', 'allège la digestion, réduit les ballonnements.', '250 g de filet de dinde - 150 g de courge musquée - 80 g de fenouil - 1 c. à café d''huile de lin - 1 pincée de cumin doux', '1. Cuire la dinde à cœur dans l''eau. 2. Courge et fenouil à la vapeur. 3. Mélanger tiède, ajouter huile et cumin au moment de servir.', 'hiver'),
('Poulet fermier & rutabaga rôti', 'Muscles & articulations', '20 min', '3 portions', 'Riche en protéines maigres + rutabaga source de potassium et de fibres.', '300 g de blanc de poulet - 120 g de rutabaga - 70 g de poireau (partie blanche) - 1 c. à café d''huile de pépins de raisin, thym séché', '1. Cuisez la courge 2. Faites cuire le saumon à la vapeur 3. Mélangez et servez tiède', 'hiver'),
('Églefin, patate douce & brocoli', 'Immunité', '25 min', '3 portions', 'soutien hépatique & prévention du stress oxydatif', '250 g d''églefin - 100 g de patate douce -  80 g de brocoli - 1 c. à café d''huile de coco, curcuma', '1. Cuire l''églefin à la vapeur jusqu''à ce qu''il soit bien cuit. 2. Éplucher et couper la patate douce, séparer les fleurettes de brocoli. 3. Cuire les légumes à la vapeur douce. 4. Mélanger l''ensemble, puis ajouter l''huile de coco et le curcuma à froid.', 'hiver'),
('Jarret de veau, céleri & pomme golden', 'Immunité et digestion', '25 min', '3 portions', 'immunité renforcée & digestion apaisée', '250 g de jarret de veau - 100 g de céleri-branche - 50 g de pomme golden (sans pépins) - 1 c. à café d''huile de chanvre - Un peu de gingembre frais râpé', '1. Cuire le veau à cœur dans une casserole d''eau bouillante. 2. Émincer le céleri et couper la pomme en dés . 3. Cuire le céleri à la vapeur douce. La pomme peut rester crue si bien tolérée. 4. Mélanger les ingrédients, ajouter l''huile et le gingembre à froid.', 'hiver'),
('Tofu ferme, carottes & châtaignes', 'digestion', '20 min', '3 portions', 'confort digestif & apport en magnésium', '200 g de tofu ferme - 100 g de carottes - 80 g de châtaignes cuites nature - 1 c. à café d''huile de sésame - 1 pincée de graines de fenouil', '1. Cuire le tofu à la vapeur pour l''attendrir. 2. Couper les carottes en rondelles et les cuire à la vapeur. 3. Émietter les châtaignes. 4. Mélanger, puis ajouter l''huile et les graines de fenouil à froid.', 'hiver'),
('Cabillaud, panais & butternut', 'Poil, digestion', '20 min', '3 portions', 'poil brillant & transit régulier', '250 g de cabillaud - 100 g de panais - 100 g de courge butternut - 1 c. à café d''huile de colza - 1/2 c. à café de levure de bière', '1. Cuire le cabillaud à la vapeur jusqu''à ce qu''il s''effeuille facilement.2. Éplucher et couper les légumes. 3. Cuire à la vapeur douce. 4. Mélanger le tout, ajouter huile et levure à froid.', 'hiver'),
('Porc maigre, topinambour & épinards', 'Digestion, microbiote', '25 min', '3 portions', 'stimulation du microbiote & assimilation des nutriments', '250 g d''échine de porc maigre - 100 g de topinambour - 80 g d''épinards - 1 c. à café d''huile de tournesol - 1/2 c. à café de poudre d''ortie', '1. Cuire le porc à cœur dans l''eau bouillante. 2. Éplucher et couper le topinambour, cuire à la vapeur. 3. Blanchir rapidement les épinards dans de l''eau chaude. 4. Assembler, puis ajouter huile et ortie en poudre à froid.', 'hiver'),
('Canard, betterave & haricots blancs', 'Energie et coeur', '30 min', '3 portions', 'énergie durable & bon fonctionnement cardiaque', '250 g de magret de canard dégraissé - 80 g de betterave cuite - 100 g de haricots blancs cuits - 1 c. à café d''huile de foie de morue - Une pincée de romarin', '1. Cuire le magret à la vapeur ou dans l''eau. 2. Couper la betterave en petits dés 3. Rincer soigneusement les haricots s''ils sont en conserve. 4. Mélanger, ajouter huile et romarin à froid.', 'hiver'),
('Lapin, potimarron & endives', 'Chiens en surpoids, stérilisés ou âgés', '25 min', '3 portions', 'repas léger pour chiens stérilisés ou peu actifs', '250 g de râble de lapin - 100 g de potimarron - 80 g d''endives - 1 c. à café d''huile de lin - 1/2 c. à café de graines de chia', '1. Cuire le lapin à cœur dans de l''eau bouillante. 2. Couper le potimarron et l''endive, cuire les deux à la vapeur douce 3.Mélanger les ingrédients, puis ajouter l''huile et les graines à froid.', 'hiver'),
('Lieu noir, salsifis & polenta', 'Articulation et transit', '20 min', '3 portions', 'confort articulaire & transit ralenti', '250 g de lieu noir - 100 g de salsifis - 80 g de polenta précuite - 1 c. à café d''huile de sardine - Un peu de persil frais haché', '1. Cuire le poisson à la vapeur. 2. Éplucher et cuire les salsifis à la vapeur douce. 3. Préparer la polenta selon les indications (à l''eau). 4. Ajouter l''huile et le persil haché juste avant de servir.', 'hiver');

-- Insert Printemps recipes (1-10)
INSERT INTO public.recipes (title, category, total_time, portions, benefits, ingredients, preparation, period) VALUES
('Poulet & courgette fraîche', 'Légèreté', '15 min', '3 portions', 'Hydratant + digeste', '250 g poulet- 200 g courgette', '1. Râpez ou cuisez légèrement la courgette 2. Faites cuire le poulet 3. Mélangez', 'printemps'),
('Dinde & petits pois', 'Vitalité', '15 min', '3 portions', 'Riche en protéines légères', '250 g dinde- 120 g petits pois', '1. Cuisez les petits pois 2. Faites cuire la dinde 3. Mélangez', 'printemps'),
('Poisson & carotte', 'Digestion', '20 min', '3 portions', 'Doux pour l''estomac', '250 g poisson blanc- 150 g carotte', '1. Cuisez carottes 2. Faites cuire poisson vapeur 3. Mélangez', 'printemps'),
('Bœuf & haricots verts', 'Énergie', '20 min', '3 portions', 'Fibres douces', '250 g bœuf- 150 g haricots verts', '1. Cuisez les haricots verts 2. Faites saisir le bœuf 3. Mélangez', 'printemps'),
('Saumon & brocoli', 'Peau & poils', '20 min', '3 portions', 'Oméga-3 + minéraux', '200 g saumon- 120 g brocoli', '1. Cuisez le brocoli 2. Cuisez le saumon vapeur 3. Mélangez', 'printemps'),
('Poulet & quinoa', 'Base équilibrée', '25 min', '3 portions', 'Énergie lente', '250 g poulet- 80 g quinoa', '1. Cuisez le quinoa 2. Faites cuire le poulet 3. Mélangez', 'printemps'),
('Dinde & courge', 'Printemps doux', '20 min', '3 portions', 'Riche en bêta-carotène', '250 g dinde- 150 g courge', '1. Cuisez la courge 2. Faites cuire la dinde 3. Mélangez', 'printemps'),
('Poisson & concombre vapeur', 'Hydratation', '10 min', '3 portions', 'Très rafraîchissant', '250 g poisson blanc- 80 g concombre (cuit léger ou cru)', '1. Faites cuire le poisson 2. Ajoutez concombre 3. Mélangez', 'printemps'),
('Bœuf & riz', 'Énergie', '20 min', '3 portions', 'Simple & efficace', '250 g bœuf- 100 g riz', '1. Cuisez le riz 2. Faites revenir le bœuf 3. Mélangez', 'printemps'),
('Sardines & courgette', 'Peau & pelage', '15 min', '3 portions', 'Oméga-3 naturels', '200 g sardines- 150 g courgette', '1. Cuisez la courgette 2. Ajoutez les sardines 3. Mélangez', 'printemps');

-- Insert Printemps recipes (11-20)
INSERT INTO public.recipes (title, category, total_time, portions, benefits, ingredients, preparation, period) VALUES
('Agneau & carotte jeune', 'Vitalité', '20 min', '3 portions', 'Riche en fer & énergie douce', '250 g agneau- 150 g carottes nouvelles', '1. Cuisez les carottes 2. Faites cuire l''agneau 3. Mélangez', 'printemps'),
('Poulet & épinards', 'Fer & vitalité', '15 min', '3 portions', 'Riche en minéraux', '250 g poulet- 80 g épinards cuits', '1. Faites cuire le poulet 2. Ajoutez les épinards cuits 3. Mélangez', 'printemps'),
('Poisson & patate douce', 'Digestion', '20 min', '3 portions', 'Haute digestibilité', '250 g poisson blanc- 150 g patate douce', '1. Cuisez la patate douce 2. Faites cuire le poisson 3. Mélangez', 'printemps'),
('Dinde & riz complet', 'Énergie lente', '25 min', '3 portions', 'Stabilise la satiété', '250 g dinde- 120 g riz complet', '1. Cuisez le riz 2. Faites cuire la dinde 3. Mélangez', 'printemps'),
('Bœuf & courgette', 'Légèreté', '15 min', '3 portions', 'Peu calorique + riche en eau', '250 g bœuf- 200 g courgette', '1. Faites cuire la courgette 2. Faites saisir le bœuf 3. Mélangez', 'printemps'),
('Poulet & haricots verts', 'Digestion douce', '15 min', '3 portions', 'Fibres légères', '250 g poulet- 150 g haricots verts', '1. Cuisez les haricots verts 2. Faites cuire le poulet 3. Mélangez', 'printemps'),
('Saumon & épinards', 'Pelage & vitalité', '15 min', '3 portions', 'Oméga-3 + fer', '200 g saumon- 80 g épinards cuits', '1. Faites cuire le saumon 2. Ajoutez les épinards 3. Mélangez', 'printemps'),
('Poisson & quinoa', 'Hypoallergénique', '20 min', '3 portions', 'Très digeste', '250 g poisson blanc- 80 g quinoa', '1. Cuisez le quinoa 2. Faites cuire le poisson 3. Mélangez', 'printemps'),
('Dinde & brocoli', 'Vitalité', '15 min', '3 portions', 'Booster immunitaire', '250 g dinde- 120 g brocoli', '1. Cuisez le brocoli 2. Faites cuire la dinde 3. Mélangez', 'printemps'),
('Poulet & carotte', 'Base douce', '15 min', '3 portions', 'Digestion parfaite', '250 g poulet- 150 g carotte', '1. Cuisez la carotte 2. Faites cuire le poulet 3. Mélangez', 'printemps');

-- Insert Printemps recipes (21-30)
INSERT INTO public.recipes (title, category, total_time, portions, benefits, ingredients, preparation, period) VALUES
('Bœuf & pomme vapeur', 'Fibres & douceur', '15 min', '3 portions', 'Régule la digestion', '250 g bœuf- 80 g pomme cuite', '1. Faites cuire la pomme à la vapeur 2. Faites saisir le bœuf 3. Mélangez', 'printemps'),
('Sardines & riz complet', 'Pelage', '20 min', '3 portions', 'Oméga-3 + énergie lente', '200 g sardines- 120 g riz complet', '1. Cuisez le riz 2. Ajoutez sardines 3. Mélangez', 'printemps'),
('Poisson & asperges (cuits)', 'Drainant', '15 min', '3 portions', 'Légèreté + minéraux', '250 g poisson blanc- 80 g asperges cuites', '1. Faites cuire le poisson 2. Ajoutez les asperges 3. Mélangez', 'printemps'),
('Poulet & fenouil', 'Digestion douce', '20 min', '3 portions', 'Anti-ballonnements naturels', '250 g poulet- 100 g fenouil', '1. Cuisez le fenouil 2. Faites cuire le poulet 3. Mélangez', 'printemps'),
('Dinde & patate douce', 'Énergie', '20 min', '3 portions', 'Bêta-carotène + vitalité', '250 g dinde- 150 g patate douce', '1. Cuisez la patate douce 2. Faites cuire la dinde 3. Mélangez', 'printemps'),
('Poisson & petits pois', 'Vitalité', '15 min', '3 portions', 'Protéines légères', '250 g poisson blanc- 120 g petits pois', '1. Cuisez les petits pois 2. Faites cuire le poisson 3. Mélangez', 'printemps'),
('Poulet & riz', 'Base équilibrée', '20 min', '3 portions', 'Recette simple & douce', '250 g poulet- 100 g riz', '1. Cuisez le riz 2. Faites cuire le poulet 3. Mélangez', 'printemps'),
('Bœuf & courge', 'Vitamines', '20 min', '3 portions', 'Antioxydants + énergie', '250 g bœuf- 150 g courge', '1. Cuisez la courge 2. Faites saisir le bœuf 3. Mélangez', 'printemps'),
('Saumon & carotte', 'Pelage & énergie', '15 min', '3 portions', 'Oméga-3 + bêta-carotène', '200 g saumon- 150 g carotte', '1. Cuisez la carotte 2. Faites cuire le saumon 3. Mélangez', 'printemps'),
('Poisson & épinards', 'Antioxydants', '10 min', '3 portions', 'Fer + vitamines', '250 g poisson blanc- 80 g épinards cuits', '1. Faites cuire le poisson 2. Ajoutez les épinards 3. Mélangez', 'printemps');

