-- Migration: Insert breeds data
-- Generated from breeds.json

INSERT INTO public.breeds (fr_name, en_name, fci_number) VALUES
  ('Affenpinscher', 'Affenpinscher', NULL),
  ('Airedale Terrier', 'Airedale Terrier', NULL),
  ('Akbash', 'Akbash', NULL),
  ('Akita Inu', 'Akita Inu', NULL),
  ('Akita américain', 'American Akita', NULL),
  ('Alangu Mastiff', 'Alangu Mastiff', NULL),
  ('Alano espagnol', 'Spanish Alano', NULL),
  ('Alaskan Klee Kai', 'Alaskan Klee Kai', NULL),
  ('Alaunt', 'Alaunt', NULL),
  ('Alopekis', 'Alopekis', NULL),
  ('Anglo-Français de petite vénerie', 'Anglo-Français de petite vénerie', '6/1.2/325'),
  ('Ariégeois', 'Ariégeois', '6/1.2/20'),
  ('Armant dog', 'Armant dog', NULL),
  ('Aïdi', 'Aidi', NULL),
  ('Aïnou', 'Ainu', NULL),
  ('Bandog', 'Bandog', NULL),
  ('Bangkaew de Thaïlande', 'Thai Bangkaew Dog', '5/5/358'),
  ('Barbet', 'Barbet', '8/3/105'),
  ('Basenji', 'Basenji', '5/6/43'),
  ('Basset ardennais', 'Basset ardennais', NULL),
  ('Basset artésien normand', 'Basset artésien normand', '6/1.3/34'),
  ('Basset bleu de Gascogne', 'Basset bleu de Gascogne', '6/1.3/35'),
  ('Basset d''Artois', 'Basset d''Artois', NULL),
  ('Basset de Westphalie', 'Basset de Westphalie', NULL),
  ('Basset des Alpes', 'Alpenländische Dachsbracke', '6/2/254'),
  ('Basset fauve de Bretagne', 'Basset fauve de Bretagne', '6/1.3/36'),
  ('Basset hound', 'Basset hound', '6/1.3/163'),
  ('Basset suédois', 'Basset suédois', NULL),
  ('Beagle', 'Beagle', '6/1.3/161'),
  ('Beagle-harrier', 'Beagle-harrier', '6/1.2/290'),
  ('Beaglier', 'Beaglier', NULL),
  ('Bedlington Terrier', 'Bedlington Terrier', '3/1/9'),
  ('Berger Belge Tervueren', 'Belge Tervueren Shepherd', '1/1/15d'),
  ('Berger Hellénique', 'Hellénique Shepherd', NULL),
  ('Berger Himalayen', 'Himalayen Shepherd', NULL),
  ('Berger Portugais ou Portuguese Shepherd Dog', 'Portugais ou Portuguese Shepherd Dog Shepherd', '1/1/93'),
  ('Berger Tahitien', 'Tahitien Shepherd', NULL),
  ('Berger allemand', 'Deutscher Schäferhund', '1/1/166'),
  ('Berger americain miniature', 'Miniature American Shepherd', NULL),
  ('Berger anglais ancestral', 'anglais ancestral Shepherd', NULL),
  ('Berger australien', 'Australian Shepherd', '1/1/342'),
  ('Berger australien miniature', 'australien miniature Shepherd', NULL),
  ('Berger basque', 'basque Shepherd', NULL),
  ('Berger belge', 'Belgian Shepherd', '1/1/15'),
  ('Berger belge Groenendael', 'belge Groenendael Shepherd', '1/1/15a'),
  ('Berger belge Laekenois', 'belge Laekenois Shepherd', '1/1/15b'),
  ('Berger belge malinois', 'belge malinois Shepherd', '1/1/15c'),
  ('Berger blanc suisse', 'blanc suisse Shepherd', '1/1/347'),
  ('Berger bulgare', 'bulgare Shepherd', NULL),
  ('Berger catalan', 'catalan Shepherd', NULL),
  ('Berger croate', 'Hrvatski Ovcar', '1/1/277'),
  ('Berger d''Anatolie', 'd''Anatolie Shepherd', NULL),
  ('Berger d''Artois', 'd''Artois Shepherd', NULL),
  ('Berger d''Asie centrale', 'Central Asia Shepherd Dog', '2/2.2/335'),
  ('Berger d''Auvergne', 'd''Auvergne Shepherd', NULL),
  ('Berger de Beauce', 'Beauceron', '1/1/44'),
  ('Berger de Bergame', 'Bergame Shepherd', NULL),
  ('Berger de Bohême', 'Chodsky pes', '1/1/364'),
  ('Berger de Bosnie-Herzégovine et de Croatie', 'Bosnie-Herzégovine et Croatie Shepherd', NULL),
  ('Berger de Brie', 'Briard', NULL),
  ('Berger de Majorque', 'Majorque Shepherd', '1/1/321'),
  ('Berger de Maremme et Abruzzes', 'Cane da Pastore Maremmano-Abruzzese', '1/1/201'),
  ('Berger de Russie méridionale ou berger d''Ukraine', 'Ioujnorousskaia Ovtcharka', '1/1/326'),
  ('Berger de Savoie ou berger des Alpes', 'Savoie ou berger Alpes Shepherd', NULL),
  ('Berger de Shiloh', 'Shiloh Shepherd', NULL),
  ('Berger de la Crau', 'la Crau Shepherd', NULL),
  ('Berger des Cévennes', 'Cévennes Shepherd', NULL),
  ('Berger des Pyrénées', 'Pyrenean Shepherd', NULL),
  ('Berger des Pyrénées à face rase', 'Pyrénées à face rase Shepherd', '1/1/138'),
  ('Berger des Pyrénées à poil long', 'Pyrénées à poil long Shepherd', '1/1/141'),
  ('Berger des Shetland', 'Shetland Sheepdog', NULL),
  ('Berger des Tatras', 'Tatras Shepherd', NULL),
  ('Berger du Caucase', 'Caucase Shepherd', NULL),
  ('Berger du Karst', 'Kraški ovčar, Kraševec', '2/2.2/278'),
  ('Berger du Languedoc Farou', 'Languedoc Farou Shepherd', NULL),
  ('Berger du Larzac', 'Larzac Shepherd', NULL),
  ('Berger finnois de Laponie', 'Lapinporokoira', '5/3/284'),
  ('Berger hollandais', 'Hollandse Herdershond', '1/1/223'),
  ('Berger islandais', 'islandais Shepherd', '5/3/289'),
  ('Berger picard', 'picard Shepherd', '1/1/176'),
  ('Berger polonais de plaine', 'Polski Owczarek Nizinny', '1/1/251'),
  ('Berger roumain', 'roumain Shepherd', NULL),
  ('Berger roumain Bucovina (de Bucovine)', 'roumain Bucovina (de Bucovine) Shepherd', '2/2.2/357'),
  ('Berger roumain de Mioritza', 'Ciobănesc românesc mioritic', '1/1/349'),
  ('Berger roumain des Carpates', 'Ciobănesc românesc carpatin', '1/1/350'),
  ('Berger yougoslave de Charplanina', 'yougoslave de Charplanina Shepherd', NULL),
  ('Bichon Bolonka', 'Bichon Bolonka', NULL),
  ('Bichon Yorkie', 'Bichon Yorkie', NULL),
  ('Bichon bolonais', 'Bolognese', NULL),
  ('Bichon havanais', 'Havanese', NULL),
  ('Bichon maltais', 'Maltese', NULL),
  ('Bichon à poil frisé', 'Bichon Frise', NULL),
  ('Biewer Yorkshire', 'Biewer Yorkshire', NULL),
  ('Billy', 'Billy', NULL),
  ('Bluetick coonhound', 'Bluetick coonhound', NULL),
  ('Boerboel', 'Boerboel', NULL),
  ('Border Terrier', 'Border Terrier', NULL),
  ('Border collie', 'Border collie', NULL),
  ('Bouche noire cur', 'Bouche noire cur', NULL),
  ('Bouledogue français', 'French Bulldog', NULL),
  ('Bouledogue jouet', 'Bouledogue jouet', NULL),
  ('Bouvier australien', 'Bouvier australien', NULL),
  ('Bouvier australien à courte queue', 'Bouvier australien à courte queue', NULL),
  ('Bouvier bernois', 'Bernese Mountain Dog', NULL),
  ('Bouvier de l''Entlebuch', 'Bouvier de l''Entlebuch', NULL),
  ('Bouvier de l’Appenzell', 'Bouvier de l’Appenzell', NULL),
  ('Bouvier des Ardennes', 'Bouvier des Ardennes', NULL),
  ('Bouvier des Flandres', 'Bouvier des Flandres', NULL),
  ('Bouvier mongol', 'Bouvier mongol', NULL),
  ('Boxer', 'Boxer', NULL),
  ('Boykin Spaniel', 'AKC-gr.Miscellaneous', NULL),
  ('Brachet allemand', 'Deutsche Bracke', '6/1.3/299'),
  ('Brachet de Styrie à poil dur', 'Peintinger Bracke', '6/1.2/62'),
  ('Brachet noir et feu', 'Brachet noir et feu', '6/1.2/63'),
  ('Brachet polonais', 'Ogar Polski', '6/1.1/52'),
  ('Brachet tyrolien', 'Tiroler Bracke', '6/1.2/68'),
  ('Braque Saint-Germain', 'Braque Saint-Germain', '7/1.1/115'),
  ('Braque allemand à poil court', 'Deutscher Kurzhaariger Vorstehhund', '7/1.1/119'),
  ('Braque d''Auvergne', 'Braque d''Auvergne', '7/1.1/180'),
  ('Braque de Burgos', 'Perdiguero de Burgos', '7/1.1/90'),
  ('Braque de Weimar', 'Weimaraner', '7/1.1/99'),
  ('Braque de Weimar à poil court', 'Braque de Weimar à poil court', '7/1.1/99a'),
  ('Braque de Weimar à poil long', 'Braque de Weimar à poil long', '7/1.1/99b'),
  ('Braque de l’Ariège', 'Braque de l’Ariège', '7/1.1/177'),
  ('Braque du Bourbonnais', 'Braque du Bourbonnais', '7/1.1/179'),
  ('Braque du Dupuy', 'Braque du Dupuy', NULL),
  ('Braque français (type Gascogne)', 'Braque français (type Gascogne)', '7/1.1/133'),
  ('Braque français (type Pyrénées)', 'Braque français (type Pyrénées)', '7/1.1/134'),
  ('Braque hongrois à poil court', 'Braque hongrois à poil court', '7/1.1/57'),
  ('Braque hongrois à poil dur', 'Braque hongrois à poil dur', '7/1.1/239'),
  ('Braque italien', 'Bracco Italiano', '7/1.1/202'),
  ('Braque portugais', 'Braque portugais', '7/1.1/187'),
  ('Braque slovaque à poil dur', 'Braque slovaque à poil dur', '7/1.1/320'),
  ('Broholmer', 'Broholmer', '2/2.1/315'),
  ('Bruno du Jura', 'Bruno du Jura', NULL),
  ('Bruno du Jura type Saint-Hubert', 'Bruno du Jura type Saint-Hubert', '6/1/125421'),
  ('Buhund norvégien', 'Norsk Buhund', '5/3/237'),
  ('Bull Boxer', 'Bull Boxer', NULL),
  ('Bull Terrier', 'Bull Terrier', '3/3/11'),
  ('Bulldog Americain', 'Bulldog Americain', NULL),
  ('Bulldog anglais', 'English Bulldog', '2/2.1/149'),
  ('Bulldog australien', 'Bulldog australien', NULL),
  ('Bulldog de sang bleu alpha', 'Bulldog de sang bleu alpha', NULL),
  ('Bullenbeißer , croisé en 1888 avec le Bulldog pour donner le Boxer', 'Bullenbeißer , croisé en 1888 avec le Bulldog pour donner le Boxer', NULL),
  ('Bullmastiff', 'Bullmastiff', '2/2.1/157'),
  ('Cairn Terrier', 'Cairn Terrier', '3/2/4'),
  ('Caniche', 'Poodle', '9/2/172'),
  ('Caniche Royal', 'Caniche Royal', NULL),
  ('Carlin', 'Pug', NULL),
  ('Cavalier King Charles Spaniel', 'Cavalier King Charles Spaniel', NULL),
  ('Cavoodle', 'Cavoodle', NULL),
  ('Charnaigre', 'Charnaigre', NULL),
  ('Chiba', 'Chiba', NULL),
  ('Chien Afghan', 'Afghan Dog', NULL),
  ('Chien Corse Cursinu', 'U Cursinu', '5/7/125420'),
  ('Chien Fila de Saint Miguel', 'Fila de Saint Miguel Dog', '2/2.1/340'),
  ('Chien africain', 'africain Dog', NULL),
  ('Chien chanteur', 'chanteur Dog', NULL),
  ('Chien chinois de Chongqing', 'East Sichuan City Dog', NULL),
  ('Chien chinois à crête', 'Chinese Crested Dog', '9/4/288'),
  ('Chien courant bernois', 'courant bernois Dog', '6/1.2/59a'),
  ('Chien courant d''Estonie', 'courant d''Estonie Dog', '6/1.2/366'),
  ('Chien courant d''Istrie à poil dur', 'Istarki Ostodlaki Gonic', '6/1.2/152'),
  ('Chien courant d''Istrie à poil ras', 'Istarki Kratkolaki Gonic', '6/1.2/151'),
  ('Chien courant de Bosnie à poil dur dit Barak', 'Bosanski Ostrodlaki Gonic Barak', '6/1.2/155'),
  ('Chien courant de Halden', 'Haldenstover', '6/1.2/267'),
  ('Chien courant de Hamilton', 'Hamiltonstövare', '6/1.2/132'),
  ('Chien courant de Hygen', 'Hygenhund', '6/1.2/266'),
  ('Chien courant de Posavatz', 'Posavski Gonic', '6/1.2/154'),
  ('Chien courant de Schiller', 'Schiller Stovare', '6/1.2/131'),
  ('Chien courant de Transylvanie', 'Erdelyi Kopov', '6/1.2/241'),
  ('Chien courant de Virelade', 'courant de Virelade Dog', NULL),
  ('Chien courant de montagne du Monténégro', 'Crnogorski Planninsk Gonic', '6/1.2/279'),
  ('Chien courant du Jura', 'Bruno du Jura', '6/1.2/59b'),
  ('Chien courant du Nord', 'courant du Nord Dog', NULL),
  ('Chien courant du Småland', 'Smalandsstovare', '6/1.2/129'),
  ('Chien courant espagnol', 'Sabueso Español', '6/1.2/204'),
  ('Chien courant finlandais', 'courant finlandais Dog', '6/1.2/51'),
  ('Chien courant grec', 'Hellinikos Ichnilatis', '6/1.2/214'),
  ('Chien courant italien', 'Segugio Italiano', NULL),
  ('Chien courant italien à poil dur', 'courant italien à poil dur Dog', '6/1.2/198'),
  ('Chien courant italien à poil ras', 'courant italien à poil ras Dog', '6/1.2/337'),
  ('Chien courant lucernois', 'courant lucernois Dog', '6/1.2/59c'),
  ('Chien courant norvégien', 'Dunker', '6/1.2/203'),
  ('Chien courant polonais', 'Gonczy Polsky', '6/1.2/354'),
  ('Chien courant schwytzois', 'courant schwytzois Dog', '6/1.2/59d'),
  ('Chien courant serbe ou chien courant des Balkans', 'Serpski Gonič', '6/1.2/150'),
  ('Chien courant slovaque', 'Slovensky´ Kopov', '6/1.2/244'),
  ('Chien courant suisse', 'courant suisse Dog', '6/1.2/59'),
  ('Chien courant tricolore serbe', 'courant tricolore serbe Dog', '6/1.2/229'),
  ('Chien créole', 'créole Dog', NULL),
  ('Chien d''Artois', 'd''Artois Dog', '6/1.2/28'),
  ('Chien d''arrêt allemand à poil dur', 'Drahthaar', '7/1.1/98'),
  ('Chien d''arrêt allemand à poil long', 'Deutsch Langhaar', '7/1.2/117'),
  ('Chien d''arrêt allemand à poil raide', 'Deutsch Stichelhaar', '7/1.1/232'),
  ('Chien d''arrêt danois ancestral', 'Gammel Dansk Hønsehund', '7/1.1/281'),
  ('Chien d''arrêt frison', 'd''arrêt frison Dog', '7/1.2/224'),
  ('Chien d''arrêt italien à poil dur', 'Spinone Italiano', '7/1.3/165'),
  ('Chien d''arrêt portugais', 'Perdigueiro Português', '7/1.1/187'),
  ('Chien d''eau américain', 'American Water Spaniel', '8/3/301'),
  ('Chien d''eau espagnol', 'Perro de agua espanol', '8/3/336'),
  ('Chien d''eau frison', 'Wetterhoun', '8/3/221'),
  ('Chien d''eau irlandais', 'Irish Water Spaniel', '8/3/124'),
  ('Chien d''eau portugais', 'Cão de agua portuguès', '8/3/37'),
  ('Chien d''eau romagnol', 'Lagotto Romagnolo', '8/3/298'),
  ('Chien d''ours de Carélie', 'Karjalankarhukoira', '5/2/48'),
  ('Chien d''oysel allemand', 'd''oysel allemand Dog', '8/2/104'),
  ('Chien d''élan norvégien gris', 'Norsk Elghund Grå', '5/2/242'),
  ('Chien d''élan norvégien noir', 'Norsk Elghund Sort', '5/2/268'),
  ('Chien d''élan suédois', 'Jämthund', '5/2/42'),
  ('Chien de Bali', 'Anjing Kintamani Bali', '5/5/362'),
  ('Chien de Canaan', 'Canaan Dog', '5/6/273'),
  ('Chien de Castro Laboreiro', 'Cão de Castro Laboreiro', '2/2.2/170'),
  ('Chien de Saint-Hubert', 'Saint-Hubert Dog', '6/1.1/84'),
  ('Chien de Taïmyr ,', 'Taïmyr , Dog', NULL),
  ('Chien de Taïwan', 'Taiwan Dog', '5/7/348'),
  ('Chien de Terre-Neuve', 'Newfoundland', '2/2.2/50'),
  ('Chien de cour italien', 'Canis Pugnax', '2/2.1/343'),
  ('Chien de ferme dano-suédois', 'ferme dano-suédois Dog', '2/1.1/356'),
  ('Chien de garenne des Canaries', 'Podenco Canario', '5/7/329'),
  ('Chien de montagne des Pyrénées', 'montagne Pyrénées Dog', '2/2.2/137'),
  ('Chien de montagne portugais', 'montagne portugais Dog', '2/2.2/173'),
  ('Chien de perdrix de Drente', 'Drentse Patrijshond', '7/1.2/224'),
  ('Chien de recherche au sang de la montagne bavaroise', 'Bayrischer Gebirgsschweisshund', '6/2/217'),
  ('Chien de recherche au sang du Hanovre', 'Hannover''scher Schweisshand', '6/2/213'),
  ('Chien du Groenland', 'Grølandshund', '5/1/274'),
  ('Chien du Haut-Poitou', 'Haut-Poitou Dog', NULL),
  ('Chien fer', 'fer Dog', NULL),
  ('Chien finnois de Laponie', 'Suomenlapinkoira', '5/3/189'),
  ('Chien léopard catahoula', 'Catahoula Cur ou Catahoula Hog Dog', NULL),
  ('Chien noir et feu pour la chasse au raton laveur', 'Black and tan Coonhound', '6/1.1/300'),
  ('Chien norvégien de macareux', 'Norsk Lundehund', '5/2/265'),
  ('Chien nu du Pérou', 'Chien nu inca', '5/6/310'),
  ('Chien nu mexicain', 'Tepeizeuintli, xoloitzcuintli', '5/6/234'),
  ('Chien paria', 'paria Dog', NULL),
  ('Chien suédois de Laponie', 'Svensk Lapphund', '5/3/135'),
  ('Chien thaïlandais à crête dorsale', 'Thaï Ridgeback Dog', '5/7/338'),
  ('Chien à loutre', 'Otterhound', '6/1.1/294'),
  ('Chien-loup de Saarloos', 'Saarlooswolfhond', '1/1/311'),
  ('Chien-loup tchécoslovaque', 'Ceskoslovenký Vlcak', '1/1/332'),
  ('Chihuahua', 'Chihuahua', '9/6/218'),
  ('Chinook', 'Chinook', NULL),
  ('Chow-Chow', 'Chow-Chow', '5/5/205'),
  ('Cimarron uruguayen', 'Cimarron urugayo', '2/2.1/353'),
  ('Cirneco de l''Étna', 'Cirneco del l''Etna', '5/7/199'),
  ('Clumber Spaniel', 'Clumber Spaniel', '8/2/109'),
  ('Cockapoo', 'Cockapoo', NULL),
  ('Cocker Spaniel américain', 'American Cocker Spaniel', '8/2/167'),
  ('Cocker Spaniel anglais', 'English Cocker Spaniel', '8/2/5'),
  ('Colley', 'Collie', NULL),
  ('Colley barbu', 'Colley barbu', '1/1/271'),
  ('Colley à poil court', 'Colley à poil court', '1/1/296'),
  ('Colley à poil long', 'Colley à poil long', '1/1/156'),
  ('Coton de Tuléar', 'Coton de Tuléar', '9/1.2/283'),
  ('Cursinu', 'Cursinu', NULL),
  ('Cão de Gado Transmontano', 'Cão de Gado Transmontano', NULL),
  ('Dalmatien', 'Dalmatian', '6/3/153'),
  ('Dandie Dinmont Terrier', 'Dandie Dinmont Terrier', '3/2/168'),
  ('Deerhound', 'Deerhound', '10/2/264'),
  ('Dingo', 'Dingo', NULL),
  ('Dingo Américain', 'Dingo Américain', NULL),
  ('Dobermann', 'Doberman', '2/1.1/143'),
  ('Dogue allemand', 'Great Dane', '2/2.1/235'),
  ('Dogue argentin', 'Dogue argentin', '2/2.1/292'),
  ('Dogue de Bordeaux', 'Dogue de Bordeaux', '2/2.1/116'),
  ('Dogue de Majorque', 'Ca de Bou', '2/2.1/249'),
  ('Dogue des Canaries', 'Dogue des Canaries', '2/2.1/346'),
  ('Dogue du Tibet', 'Dogue du Tibet', '2/2.2/230'),
  ('English Coonhound', 'American English Coonhound,Redtick Coonhound', NULL),
  ('English Springer Spaniel', 'English Springer Spaniel', '8/2/125'),
  ('Esquimau américain', 'American Eskimo Dog', NULL),
  ('Esquimau canadien', 'Esquimau canadien', '5/1/211'),
  ('Estonian Hound', 'Estonian Hound', NULL),
  ('Eurasier', 'Eurasier', '5/5/291'),
  ('Field Spaniel', 'Field Spaniel', '8/2/123'),
  ('Fila Brasileiro', 'Fila Brasileiro', '2/2.1/225'),
  ('Fox Terrier', 'Fox Terrier', NULL),
  ('Fox-terrier à poil dur', 'Wire', '3/1/169'),
  ('Fox-terrier à poil lisse )', 'Fox-terrier à poil lisse )', '3/1/12'),
  ('Foxhound américain', 'American Foxhound', '6/1.1/303'),
  ('Foxhound anglais', 'English Foxhound', '6/1.1/159'),
  ('Français blanc et noir', 'Français blanc et noir', '6/1.1/220'),
  ('Français blanc et orange', 'Français blanc et orange', '6/1.1/316'),
  ('Français tricolore', 'Français tricolore', '6/1.1/219'),
  ('Gascon saintongeois', 'Gascon saintongeois', '6/1.1/21'),
  ('Goldador', 'Goldador', NULL),
  ('Golden Retriever', 'Golden Retriever', '8/1/111'),
  ('Goldendoodle', 'Goldendoodle', NULL),
  ('Grand Münsterländer', 'Grand Münsterländer', '7/1.2/118'),
  ('Grand anglo-français blanc et noir', 'Grand anglo-français blanc et noir', '6/1.1/323'),
  ('Grand anglo-français blanc et orange', 'Grand anglo-français blanc et orange', '6/1.1/324'),
  ('Grand anglo-français tricolore', 'Grand anglo-français tricolore', '6/1.1/322'),
  ('Grand basset griffon vendéen', 'Grand basset griffon vendéen', '6/1.3/33'),
  ('Grand bleu de Gascogne', 'Grand bleu de Gascogne', '6/1.1/22'),
  ('Grand bouvier suisse', 'Grosser Schweizer Sennenhund', '2/3/58'),
  ('Grand griffon vendéen', 'Grand griffon vendéen', '6/1.1/282'),
  ('Grand spitz', 'Deutscher Großspitz', '5/4/97b'),
  ('Griffon belge', 'Griffon belge', '9/3.1/81'),
  ('Griffon bleu de Gascogne', 'Griffon bleu de Gascogne', '6/1.2/32'),
  ('Griffon boulet à poil laineux', 'Griffon boulet à poil laineux', NULL),
  ('Griffon bruxellois', 'Griffon bruxellois', '9/3.1/80'),
  ('Griffon d''arrêt tchèque', 'Ceský Fousek', '7/1.3/245'),
  ('Griffon d''arrêt à poil dur Korthals', 'Korthals', '7/1.3/107'),
  ('Griffon de Bresse', 'Griffon de Bresse', NULL),
  ('Griffon fauve de Bretagne', 'Griffon fauve de Bretagne', '6/1.2/66'),
  ('Griffon nivernais', 'Griffon nivernais', '6/1.2/17'),
  ('Griffon vendéen', 'Griffon vendéen', '6/1.2/19'),
  ('Harrier', 'Harrier', '6/1.2/295'),
  ('Hovawart', 'Hovawart', '2/2.2/190'),
  ('Huntaway', 'Huntaway', NULL),
  ('Husky de Sakhaline', 'Husky de Sakhaline', NULL),
  ('Husky sibérien', 'Husky sibérien', '5/1/270'),
  ('Intimidateur américain', 'Intimidateur américain', NULL),
  ('Irish wolfhound', 'Irish wolfhound', '10/2/160'),
  ('Jack Russell Terrier', 'Jack Russell Terrier', '3/2/345'),
  ('Jindo coréen', 'Jindo coréen', '5/5/334'),
  ('Jouet Manchester terrier', 'Jouet Manchester terrier', NULL),
  ('Jouet fox terrier', 'Jouet fox terrier', NULL),
  ('Jug', 'Jug', NULL),
  ('Kai', 'Kai', '5/5/317'),
  ('Kangal Dog', 'Kangal Dog', '2/2.2/331'),
  ('Keeshond', 'Keeshond', '5/4/97a'),
  ('Kelpie australien', 'Kelpie australien', '1/1/293'),
  ('Kerry beagle', 'Kerry beagle', NULL),
  ('King Charles Spaniel', 'King Charles Spaniel', '9/7/128'),
  ('King Shepherd', 'King Shepherd', NULL),
  ('Kishu', 'Kishu', '5/5/318'),
  ('Komondor', 'Komondor', '1/1/53'),
  ('Kooikerhondje', 'Kooikerhondje', '8/2/314'),
  ('Koolie', 'Australian koolie', NULL),
  ('Kromfohrländer', 'Kromfohrländer', '9/10/192'),
  ('Kuchi dog', 'Kuchi dog', NULL),
  ('Kuvasz', 'Kuvasz', '1/1/54'),
  ('Kyi Leo', 'Kyi Leo', NULL),
  ('Kyi apso tibétain', 'Kyi apso tibétain', NULL),
  ('Labernois', 'Saint-Pierre', NULL),
  ('Labrabull', 'Labrabull', NULL),
  ('Labradinger', 'Labradinger', NULL),
  ('Labradoodle', 'Labradoodle', NULL),
  ('Labrador', 'Labrador', '8/1/122'),
  ('Labrastaff', 'Labrastaff', NULL),
  ('Laika de Iakoutie', 'Yakutskaïa Laïka', '5/1/365'),
  ('Lakeland Terrier', 'Lakeland Terrier', '3/1/70'),
  ('Lancashire Heeler', 'Lancashire Heeler', '1/1/360'),
  ('Landseer (Landseer)', 'Landseer (Landseer)', '2/2.2/226'),
  ('Laïka de Sibérie occidentale', 'Zapadno-Sibirskaïa Laïka', '5/2/306'),
  ('Laïka de Sibérie orientale', 'Vostotchno-Sibirskaïa Laïka', '5/2/305'),
  ('Laïka russo-européen', 'Russo-Evropeïskaïa Laïka', '5/2/304'),
  ('Leonberg', 'Leonberg', '2/2.2/145'),
  ('Levesque', 'Levesque', NULL),
  ('Levrette italienne', 'Levrette italienne', '10/3/200'),
  ('Lhassa Apso', 'Lhasa Apso', '9/5/227'),
  ('Lithuanian Hound', 'Lithuanian Hound', NULL),
  ('Longdog', 'Longdog', NULL),
  ('Loulou de Poméranie', 'Loulou de Poméranie', '5/4/97e'),
  ('Lurcher', 'Lurcher', NULL),
  ('Lévrier Bakhmull', 'Lévrier Bakhmull', NULL),
  ('Lévrier Caravan hound', 'Karwani', NULL),
  ('Lévrier Chortaj', 'Khortaï', NULL),
  ('Lévrier Rampur', 'Lévrier Rampur', NULL),
  ('Lévrier Taïgan', 'Lévrier Taïgan', NULL),
  ('Lévrier afghan', 'Afghan hound', '10/1/228'),
  ('Lévrier anglais', 'Greyhound', '10/3/158'),
  ('Lévrier arabe', 'Sloughi ou lévrier berbère', '10/3/188'),
  ('Lévrier australien', 'Lévrier australien', NULL),
  ('Lévrier azawakh', 'Lévrier azawakh', '10/3/307'),
  ('Lévrier de Pharaon', 'Pharaoh Hound', '5/6/248'),
  ('Lévrier de soie', 'Silken Windhound', NULL),
  ('Lévrier des Baléares', 'Lévrier des Baléares', '5/7/89'),
  ('Lévrier des Canaries', 'Lévrier des Canaries', '5/7/329'),
  ('Lévrier espagnol', 'Galgo espagnol', '10/3/285'),
  ('Lévrier grec', 'Lévrier grec', NULL),
  ('Lévrier hongrois', 'Magyar Agar', '10/3/240'),
  ('Lévrier irlandais', 'Irish wolfhound', '10/2/160'),
  ('Lévrier persan', 'Saluki ou Salouki', '10/1/269'),
  ('Lévrier polonais', 'Chart Polski', '10/3/333'),
  ('Lévrier portugais', 'Podengo Português', '5/7/94'),
  ('Lévrier russe', 'Barzoï', '10/1/193'),
  ('Lévrier whippet', 'Lévrier whippet', '10/3/162'),
  ('Lévrier écossais', 'Deerhound', '10/2/164'),
  ('Mackenzie River husky', 'Mackenzie River husky', NULL),
  ('Mal-shi', 'Mal-shi', NULL),
  ('Malamute d''Alaska', 'Alaskan Malamute', '5/1/243'),
  ('Malinois', 'Malinois', NULL),
  ('Maltipoo', 'Maltipoo', NULL),
  ('Manchester terrier', 'Manchester terrier', '3/1/71'),
  ('Mastiff', 'Mastiff', '2/2.1/264'),
  ('Mastiff d''Anatolie', 'Aksaray Malakli', NULL),
  ('Miniature Fox Terrier', 'Miniature Fox Terrier', NULL),
  ('Mountain Cur', 'Mountain Cur', NULL),
  ('Mudi', 'Mudi', '1/1/238'),
  ('Mâtin belge', 'Mâtin belge', '2/2/69'),
  ('Mâtin de l''Alentejo', 'Rafeiro do Alentejo', '2/2.2/96'),
  ('Mâtin des Pyrénées', 'Mastin Pirineo', '2/2.2/92'),
  ('Mâtin espagnol', 'Mastin español', '2/2.2/91'),
  ('Mâtin napolitain', 'Mastino napolitano', '2/2.1/197'),
  ('Mâtin transmontano', 'Mâtin transmontano', '2/2.2/368'),
  ('Norfolk Terrier', 'UKC-gr.Terrier', '3/2/272'),
  ('Norwich Terrier', 'UKC-gr.Terrier', '3/2/72'),
  ('Old English Bulldog', 'Old English Bulldog', NULL),
  ('Papillon', 'Papillon', '9/9/77a'),
  ('Patterdale Terrier', 'Patterdale Terrier', NULL),
  ('Perro fino Colombiano', 'Perro fino Colombiano', NULL),
  ('Perro sin pelo del Perú', 'Perro sin pelo del Perú', '5/6/310'),
  ('Petit Münsterländer', 'Petit Münsterländer', '7/1.2/102'),
  ('Petit basset griffon vendéen', 'Petit basset griffon vendéen', '6/1.3/67'),
  ('Petit bleu de Gascogne', 'Petit bleu de Gascogne', '6/1.2/31'),
  ('Petit brabançon', 'Petit brabançon', '9/3.2/82'),
  ('Petit chien courant bernois', 'Petit chien courant bernois', NULL),
  ('Petit chien courant lucernois', 'Petit chien courant lucernois', NULL),
  ('Petit chien courant schwytzois', 'Petit chien courant schwytzois', NULL),
  ('Petit chien courant suisse', 'Petit chien courant suisse', '6/1.3/60'),
  ('Petit chien hollandais de chasse', 'Petit chien hollandais de chasse', '8/2/314'),
  ('Petit chien lion', 'Petit chien lion', '9/1.3/233'),
  ('Petit chien russe', 'Russian Toy Terrier', '9/9/352'),
  ('Petit lévrier italien', 'Petit lévrier italien', '10/3/200'),
  ('Petit spitz', 'Deutscher Kleinspitz', '5/4/97d'),
  ('Phalène', 'Phalène', '9/9/77b'),
  ('Pinscher allemand', 'Pinscher allemand', '2/1.1/184'),
  ('Pinscher autrichien', 'Osterreichischer Pinscher', '2/1.1/64'),
  ('Pinscher nain', 'Zwergpinscher', '2/1.1/185'),
  ('Plott Hound', 'Plott Hound', NULL),
  ('Pointer', 'English Pointer', '7/2.1/1'),
  ('Poitevin', 'Poitevin', '6/1.2/24'),
  ('Porcelaine', 'Porcelaine', '6/1.2/30'),
  ('Pudelpointer', 'Pudelpointer', '7/1.1/216'),
  ('Puggle', 'Puggle', NULL),
  ('Puli', 'Puli', '1/1/55'),
  ('Pumi', 'Pumi', '1/1/56'),
  ('Pékinois', 'Pekingese', '9/8/207'),
  ('Ratier de Prague', 'Pražský krysařík', '9/9/363'),
  ('Ratonero Bodeguero Andaluz', 'Ratonero Bodeguero Andaluz', NULL),
  ('Redbone Coonhound', 'Redbone Coonhound', NULL),
  ('Retriever de la Nouvelle-Écosse', 'Nova Scotia Duck Tolling Retriever', '8/1/312'),
  ('Retriever de la baie de Chesapeake', 'Chesapeake Bay Retriever', '8/1/263'),
  ('Retriever du Labrador', 'Retriever du Labrador', '8/1/122'),
  ('Retriever à poil bouclé', 'Curly Coated Retriever', '8/1/110'),
  ('Retriever à poil plat', 'Flat Coated Retriever', '8/1/121'),
  ('Rhodesian Ridgeback', 'Rhodesian Ridgeback', '6/3/146'),
  ('Rottweiler', 'Rottweiler', '2/2.1/147'),
  ('Royal Bourbon', 'Royal Bourbon', NULL),
  ('Sabueso español', 'Sabueso español', '6/1.2/204'),
  ('Saint-bernard', 'Saint Bernard', '2/2.2/61'),
  ('Samoyède', 'Samoyed', NULL),
  ('Sapsali', 'Sapsali', NULL),
  ('Schapendoes néerlandais', 'Nederlandse Schapendoes', '1/1/313'),
  ('Schillerstövare', 'Schillerstövare', '6/1.2/131'),
  ('Schipperke', 'Schipperke', '1/1/83'),
  ('Schnauzer géant', 'Schnauzer géant', '2/1.2/181'),
  ('Schnauzer moyen', 'Schnauzer moyen', '2/1.2/182'),
  ('Schnauzer nain', 'Schnauzer nain', '2/1.2/183'),
  ('Schnoodle', 'Schnoodle', NULL),
  ('Schweizer Laufhund', 'Schweizer Laufhund', NULL),
  ('Sealyham Terrier', 'Sealyham Terrier', NULL),
  ('Segugio Maremmano', 'Segugio Maremmano', NULL),
  ('Setter Gordon', 'Setter Gordon', NULL),
  ('Setter anglais', 'Setter anglais', NULL),
  ('Setter irlandais rouge', 'Setter irlandais rouge', NULL),
  ('Setter irlandais rouge et blanc', 'Setter irlandais rouge et blanc', NULL),
  ('Shar Pei', 'Shar Pei', NULL),
  ('Sheeoadoodle', 'Sheeoadoodle', NULL),
  ('Shiba Inu', 'Shiba Inu', NULL),
  ('Shih Tzu', 'Shih Tzu', NULL),
  ('Shih-poo', 'Shih-poo', NULL),
  ('Shikoku', 'Shikoku', NULL),
  ('Skye Terrier', 'Skye Terrier', NULL),
  ('Smous des Pays-Bas', 'Smous des Pays-Bas', NULL),
  ('Spitz Loup', 'Keeshond, chien-loup', '5/4/97a'),
  ('Spitz allemand', 'Spitz allemand', NULL),
  ('Spitz de Norrbotten', 'Norrbottenspets', '5/2/276'),
  ('Spitz des Wisigoths', 'Spitz des Wisigoths', '5/3/14'),
  ('Spitz finlandais', 'Suomenpystykorva', '5/2/49'),
  ('Spitz italien', 'Volpino Italiano', '5/4/195'),
  ('Spitz japonais', 'Nihon Supittsu', '5/5/262'),
  ('Spitz moyen', 'Deutscher Mittelspitz', '5/4/97c'),
  ('Spitz nain', 'Spitz nain', '5/4/97e'),
  ('Sporting Lucas Terrier', 'Sporting Lucas Terrier', NULL),
  ('Springer spaniel', 'Springer spaniel', NULL),
  ('Staffordshire Bull Terrier ou staffie', 'Staffordshire Bull Terrier ou staffie', '3/3/76'),
  ('Staffordshire Terrier américain', 'Staffordshire Terrier américain', '3/3/286'),
  ('Stephens Cur', 'Stephens Cur', NULL),
  ('Sussex Spaniel', 'Sussex Spaniel', '8/2/127'),
  ('Talbot', 'Talbot', NULL),
  ('Tamaskan', 'Utonogan', NULL),
  ('Tchouvatch slovaque', 'Slovenský Cuvac', '1/1/142'),
  ('Teckel', 'Dachshund', '4/1/148'),
  ('Teddy Roosevelt Terrier', 'UKC-gr.Terrier', NULL),
  ('Tenterfield Terrier', 'Tenterfield Terrier', NULL),
  ('Terre-neuve', 'Newfoundland', '2/2.2/50'),
  ('Terrier Glen of Imaal', 'Terrier Glen of Imaal', NULL),
  ('Terrier Kerry Blue', 'Kerry Blue Terrier', '3/1/3'),
  ('Terrier anglais d''agrément noir et feu', 'Terrier anglais d''agrément noir et feu', NULL),
  ('Terrier australien', 'Terrier australien', NULL),
  ('Terrier australien à poil soyeux', 'Terrier australien à poil soyeux', NULL),
  ('Terrier blanc des Highlands de l''Ouest', 'Terrier blanc des Highlands de l''Ouest', NULL),
  ('Terrier brésilien', 'Terrier brésilien', NULL),
  ('Terrier de Boston', 'Boston Terrier', '9/11/140'),
  ('Terrier de chasse allemand', 'Terrier de chasse allemand', NULL),
  ('Terrier du Révérend Russel', 'Parson Russel Terrier', '3/1/339'),
  ('Terrier gallois', 'Welsh Terrier', '3/1/78'),
  ('Terrier glabre américain', 'Terrier glabre américain', NULL),
  ('Terrier irlandais', 'Irish Terrier', '3/1/139'),
  ('Terrier irlandais à poil doux', 'Irish Soft Coated Wheaten Terrier', '3/1/40'),
  ('Terrier japonais', 'UKC-gr.Terrier', '3/2/259'),
  ('Terrier noir', 'Tchiorny Terrier', '2/1.4/327'),
  ('Terrier tchèque', 'Cesky Terrier', '3/2/246'),
  ('Terrier tibétain', 'Terrier tibétain', NULL),
  ('Terrier écossais', 'Terrier écossais', NULL),
  ('Texas Heeler', 'Texas Heeler', NULL),
  ('Tosa', 'Tosa', NULL),
  ('Traîneau de Sibérie de Seppala', 'Traîneau de Sibérie de Seppala', NULL),
  ('Treeing Cur', 'Treeing Cur', NULL),
  ('Treeing Tennessee Brindle', 'Treeing Tennessee Brindle', NULL),
  ('Treeing Walker Coonhound', 'Treeing Walker Coonhound', NULL),
  ('Welsh Corgi Cardigan', 'Welsh Corgi Cardigan', NULL),
  ('Welsh Corgi Pembroke', 'Welsh Corgi Pembroke', NULL),
  ('Yorkillon', 'Yorkillon', NULL),
  ('Yorkipoo', 'Yorkipoo', NULL),
  ('Yorkshire Terrier', 'Yorkshire Terrier', NULL),
  ('Zuchon, Shichon', 'Zuchon, Shichon', NULL),
  ('pit-bull', 'pit-bull', NULL),
  ('Épagneul bleu de Picardie', 'Épagneul bleu de Picardie', '7/1.2/106'),
  ('Épagneul breton', 'Brittany Spaniel', '7/1.2/95'),
  ('Épagneul de Münster', 'Épagneul de Münster', NULL),
  ('Épagneul de Pont-Audemer', 'Épagneul de Pont-Audemer', '7/1.2/114'),
  ('Épagneul de Saint-Usuge', 'Épagneul de Saint-Usuge', NULL),
  ('Épagneul français', 'Épagneul français', '7/1.2/75'),
  ('Épagneul japonais', 'Chin', '9/8/206'),
  ('Épagneul nain continental', 'Épagneul nain continental', '9/9/77'),
  ('Épagneul nain continental papillon', 'Papillon', '9/9/77a'),
  ('Épagneul nain continental phalène', 'Phalène', '9/9/77b'),
  ('Épagneul picard', 'Épagneul picard', '7/1.2/108'),
  ('Épagneul springer gallois', 'Épagneul springer gallois', NULL),
  ('Épagneul tibétain', 'Tibetan Spaniel', '9/5/231');

-- Verify insertion
DO $$ BEGIN RAISE NOTICE 'Inserted % breeds', (SELECT COUNT(*) FROM public.breeds); END $$;
